spring.application.name=authx
#server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/dass_authx
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=cfdbc2c85ffc93
spring.mail.password=49f814601b4184

server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=5m
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict

spring.web.error.whitelabel.enabled=false